-- Polymarket Dashboard strategy lifecycle registry.
-- The pd_ prefix is derived from polymarket-dashboard.

create table public.pd_strategies (
  strategy_id text primary key,
  display_name text not null,
  codename text not null,
  thesis text not null,
  strategy_kind text not null check (
    strategy_kind in ('LIVE_TRADING', 'SIMULATION_RESEARCH', 'INFRA_RESEARCH', 'LEGACY_TRADING')
  ),
  lifecycle_stage text not null check (
    lifecycle_stage in (
      'IDEA',
      'IMPLEMENTING',
      'IMPLEMENTED',
      'SIMULATION',
      'LIVE_VALIDATION',
      'STABILIZATION',
      'PRODUCTION',
      'CLOSED'
    )
  ),
  operating_status text not null check (
    operating_status in ('ACTIVE', 'PAUSED', 'CLOSE_ONLY', 'INACTIVE', 'CLOSED')
  ),
  evaluation_started_at timestamptz,
  phase_started_at timestamptz,
  evaluation_horizon_days integer check (evaluation_horizon_days is null or evaluation_horizon_days > 0),
  current_summary text not null,
  attention_note text,
  source_ref text not null,
  hidden_by_default boolean not null default false,
  sort_order integer not null default 1000,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pd_strategies_id_format check (strategy_id ~ '^golden-[a-z0-9-]+$'),
  constraint pd_strategies_closed_consistency check (
    lifecycle_stage <> 'CLOSED'
    or (operating_status in ('CLOSE_ONLY', 'CLOSED') and hidden_by_default)
  )
);

comment on table public.pd_strategies is
  'Current strategy lifecycle registry. Stage and operating status are deliberately separate.';
comment on column public.pd_strategies.source_ref is
  'Repository-relative evidence document used to justify the current lifecycle classification.';

create table public.pd_jenkins_jobs (
  job_name text primary key,
  strategy_id text not null references public.pd_strategies(strategy_id) on update cascade on delete restrict,
  runtime_job text,
  mode text not null check (mode in ('LIVE', 'SIMULATION', 'SHADOW', 'CLOSE_ONLY', 'RESEARCH')),
  treatment_label text,
  schedule text,
  expected_cadence_minutes integer check (
    expected_cadence_minutes is null or expected_cadence_minutes > 0
  ),
  workspace_class text not null default 'INTERNAL' check (
    workspace_class in ('INTERNAL', 'EXTERNAL', 'UNKNOWN')
  ),
  buildable boolean,
  enabled boolean,
  in_queue boolean,
  building boolean,
  job_color text,
  last_build_number integer,
  last_build_status text,
  last_build_started_at timestamptz,
  last_build_duration_ms bigint check (last_build_duration_ms is null or last_build_duration_ms >= 0),
  config_sha256 text,
  observed_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pd_jenkins_jobs_name_nonempty check (btrim(job_name) <> '')
);

comment on table public.pd_jenkins_jobs is
  'Jenkins job-to-strategy routing plus read-only health observations collected from the LAN.';
comment on column public.pd_jenkins_jobs.observed_at is
  'Timestamp of the latest successful Jenkins API observation; null means never observed.';

create table public.pd_strategy_checkpoints (
  checkpoint_id text primary key,
  strategy_id text not null references public.pd_strategies(strategy_id) on update cascade on delete cascade,
  checkpoint_type text not null check (
    checkpoint_type in (
      'COLLECTION_HEALTH',
      'DAY_7_REVIEW',
      'DAY_30_REVIEW',
      'MONTHLY_REVIEW',
      'STABILITY_GATE',
      'PROFITABILITY_REVIEW',
      'DEPLOYMENT_DECISION'
    )
  ),
  title text not null,
  due_at timestamptz,
  status text not null default 'PENDING' check (
    status in ('PENDING', 'COMPLETED', 'BLOCKED', 'CANCELLED')
  ),
  completed_at timestamptz,
  instructions text not null,
  source_ref text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pd_strategy_checkpoints_completion check (
    (status = 'COMPLETED' and completed_at is not null)
    or (status <> 'COMPLETED' and completed_at is null)
  )
);

comment on table public.pd_strategy_checkpoints is
  'Review calendar. DUE and OVERDUE are derived at read time so deadlines do not require cron updates.';

create table public.pd_sync_runs (
  sync_run_id bigint generated by default as identity primary key,
  collector_name text not null,
  started_at timestamptz not null,
  finished_at timestamptz,
  status text not null check (status in ('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED')),
  jobs_expected integer not null default 0 check (jobs_expected >= 0),
  jobs_observed integer not null default 0 check (jobs_observed >= 0),
  jobs_failed integer not null default 0 check (jobs_failed >= 0),
  error_summary text,
  created_at timestamptz not null default now(),
  constraint pd_sync_runs_finished check (
    (status = 'RUNNING' and finished_at is null)
    or (status <> 'RUNNING' and finished_at is not null)
  ),
  constraint pd_sync_runs_counts check (jobs_observed + jobs_failed <= jobs_expected)
);

comment on table public.pd_sync_runs is
  'Secret-free health history for the LAN Jenkins metadata collector.';

create index pd_strategies_stage_sort_idx
  on public.pd_strategies (lifecycle_stage, sort_order, strategy_id);
create index pd_jenkins_jobs_strategy_idx
  on public.pd_jenkins_jobs (strategy_id, job_name);
create index pd_jenkins_jobs_observed_idx
  on public.pd_jenkins_jobs (observed_at desc nulls last);
create index pd_strategy_checkpoints_due_idx
  on public.pd_strategy_checkpoints (status, due_at nulls last);
create index pd_strategy_checkpoints_strategy_idx
  on public.pd_strategy_checkpoints (strategy_id, due_at nulls last);
create index pd_sync_runs_started_idx
  on public.pd_sync_runs (started_at desc);

create or replace function public.pd_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger pd_strategies_set_updated_at
before update on public.pd_strategies
for each row execute function public.pd_set_updated_at();

create trigger pd_jenkins_jobs_set_updated_at
before update on public.pd_jenkins_jobs
for each row execute function public.pd_set_updated_at();

create trigger pd_strategy_checkpoints_set_updated_at
before update on public.pd_strategy_checkpoints
for each row execute function public.pd_set_updated_at();

alter table public.pd_strategies enable row level security;
alter table public.pd_jenkins_jobs enable row level security;
alter table public.pd_strategy_checkpoints enable row level security;
alter table public.pd_sync_runs enable row level security;

revoke all on table public.pd_strategies from anon, authenticated;
revoke all on table public.pd_jenkins_jobs from anon, authenticated;
revoke all on table public.pd_strategy_checkpoints from anon, authenticated;
revoke all on table public.pd_sync_runs from anon, authenticated;
revoke all on sequence public.pd_sync_runs_sync_run_id_seq from anon, authenticated;
